# Generated by Django 3.1.5 on 2021-01-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('date', models.DateField()),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
