# Generated by Django 3.1.5 on 2021-01-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('class_number', models.IntegerField()),
                ('group', models.CharField(max_length=255)),
                ('is_super_user', models.BooleanField()),
            ],
        ),
    ]
