# Generated by Django 3.1.5 on 2021-01-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_number',
        ),
    ]
